### ISSUE TITLE
Put shared files on a subpath

### ISSUE THREAD

**Issue by theAlevan** [RoastSlav/quickdrop#4]
Currently, files are shared through the root path:

https://quickdrop.com/file/7c84f8c8-75da-4b92-ab8e-84cb26e4384e

While creating a subpath for them would allow for more granulated external IdP ACL rules, like this (for example the addtiton of a **share** subpath):

https://quickdrop.com/file/share/7c84f8c8-75da-4b92-ab8e-84cb26e4384e

Practical usage: Keeping the quickdrop.com/file path authenticated, while letting the quickdrop.com/file/share subpath unauthenticated, making it possible only for authenticated users to upload file, while unauthenticated users still are able to download them.

**Comment by RoastSlav** [comment]
Thanks for the suggestion! I get what you’re going for with the /share subpath idea, but it wouldn’t work as is because it could bypass the app-level and file-level passwords. This would make files accessible just by changing the URL, which could be a security risk.

That said, I understand your point about allowing unauthenticated users to download files while keeping uploads restricted to authenticated users. To address this, I will add a shareable link feature where users can create links that bypass passwords for specific files. These links will have options like expiration dates and can be disabled when needed.

I think this approach will achieve what you’re suggesting but with more control and security. Let me know if I misunderstood, or you have an idea on how to improve it further.

**Comment by RoastSlav** [comment]
You can now download the new update that has the feature i mentioned
